### ISSUE TITLE
Unable to register

### ISSUE THREAD

**Issue by jk563** [rschroll/rmfuse#45]
Unfortunately it looks like this no longer works? Following the instructions given I keep hitting this auth issue that may be related to other recent tickets.

Hopefully this is just a me problem and there's something I missed

```
$ rmfuse ~/remarkable
This reMarkable client needs to be registered with the reMarkable
cloud. To do this, please visit
    https://my.remarkable.com/connect/desktop
to get a one-time code.

(You may be prompted to log into your reMarkable cloud account. If
this happens, you may not be redirected to the one-time code page.
In this case, you may open the above link a second time to get the
code.)

Enter the one-time code: [redacted]
Error in sys.excepthook:
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/trio/_core/_multierror.py", line 438, in trio_excepthook
    for chunk in traceback.format_exception(etype, value, tb):
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/traceback.py", line 135, in format_exception
    te = TracebackException(type(value), value, tb, limit=limit, compact=True)
TypeError: traceback_exception_init() got an unexpected keyword argument 'compact'

Original exception was:
Traceback (most recent call last):
  File "/opt/homebrew/bin/rmfuse", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.10/site-packages/rmfuse/fuse.py", line 548, in main
    get_client_s()
  File "/opt/homebrew/lib/python3.10/site-packages/rmcl/sync.py", line 15, in sfunc
    return trio.run(runner)
  File "/opt/homebrew/lib/python3.10/site-packages/trio/_core/_run.py", line 1932, in run
    raise runner.main_task_outcome.error
  File "/opt/homebrew/lib/python3.10/site-packages/rmcl/sync.py", line 14, in runner
    return await afunc(*args, **kw)
  File "/opt/homebrew/lib/python3.10/site-packages/rmcl/api.py", line 389, in get_client
    await _client.prompt_register_device()
  File "/opt/homebrew/lib/python3.10/site-packages/rmcl/api.py", line 179, in prompt_register_device
    return await self.register_device(code)
  File "/opt/homebrew/lib/python3.10/site-packages/rmcl/api.py", line 158, in register_device
    raise AuthError(f"Could not register device (status code {response.status_code})")
rmcl.exceptions.AuthError: Could not register device (status code 500)
```

**Comment by Xaver106** [comment]
The new Link to register a new device seems to be https://my.remarkable.com/#desktop. 
But it looks like remarkable added some sort of check to see if the connecting app is official.
The code I get from the new link fails in rmfusion with the following error:
```rmfuse ~/remarkable
/home/xaver106/.local/lib/python3.11/site-packages/trio/_core/_multierror.py:502: RuntimeWarning: You seem to already have a custom sys.excepthook handler installed. I'll skip installing Trio's custom handler, but this means MultiErrors will not show full tracebacks.
  warnings.warn(
This reMarkable client needs to be registered with the reMarkable
cloud. To do this, please visit
    https://my.remarkable.com/connect/desktop
to get a one-time code.

(You may be prompted to log into your reMarkable cloud account. If
this happens, you may not be redirected to the one-time code page.
In this case, you may open the above link a second time to get the
code.)

Enter the one-time code: xxxxxxxx
Traceback (most recent call last):
  File "/home/xaver106/.local/bin/rmfuse", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/xaver106/.local/lib/python3.11/site-packages/rmfuse/fuse.py", line 548, in main
    get_client_s()
  File "/home/xaver106/.local/lib/python3.11/site-packages/rmcl/sync.py", line 15, in sfunc
    return trio.run(runner)
           ^^^^^^^^^^^^^^^^
  File "/home/xaver106/.local/lib/python3.11/site-packages/trio/_core/_run.py", line 1932, in run
    raise runner.main_task_outcome.error
  File "/home/xaver106/.local/lib/python3.11/site-packages/rmcl/sync.py", line 14, in runner
    return await afunc(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xaver106/.local/lib/python3.11/site-packages/rmcl/api.py", line 389, in get_client
    await _client.prompt_register_device()
  File "/home/xaver106/.local/lib/python3.11/site-packages/rmcl/api.py", line 179, in prompt_register_device
    return await self.register_device(code)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xaver106/.local/lib/python3.11/site-packages/rmcl/api.py", line 158, in register_device
    raise AuthError(f"Could not register device (status code {response.status_code})")
rmcl.exceptions.AuthError: Could not register device (status code 500)
```

**Comment by jaker-dotcom** [comment]
can reproduce

**Comment by JeremyDarbellay** [comment]
Reproduced.
Used link provided by Xaver106 (thank you @Xaver106 )
Same error as Xaver106, error 500 by rmcl

**Comment by simisimis** [comment]
getting 500 as well... Just as I was about to get my hopes up..

**Comment by JeremyDarbellay** [comment]
@simisimis Ended up using wine and official app, it works

**Comment by IshmaelBelghazi** [comment]
Same error

**Comment by TudbuT** [comment]
can reproduce
